version: '3'

services:
  app:
    container_name: ci3-app
    image: ci3
    build:
      context: .
      dockerfile: docker/v2/Dockerfile
    #env_file:
    #  - .env
    ports:
      - 8080:80
    #volumes:
    #  - .:/var/lib/nginx/html/
    #  - /var/www/html/vendor

  db:
    container_name: ci3-db
    image: mariadb
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    #volumes:
    #  ./database:/var/lib/mysql
    #  ./db.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    container_name: ci3-pma
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8081:80
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app

volumes:
  persistent: